name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Name of the release"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: bun install

      - name: Update package.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.inputs.version }}\"/" ./package.json

      - name: Build
        run: |
          bun run build
          cp dist/index.user.js /tmp/index.user.js

      - name: Commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add package.json
          git commit -m "release: v${{ github.event.inputs.version }}"
          git tag v${{ github.event.inputs.version }}

      - name: Switch to release branch
        run: |
          git fetch origin built
          git switch built -f
          git pull origin built

      - name: Copy built file
        run: |
          git clean -df
          cp /tmp/index.user.js index.user.js
          git add index.user.js
          git commit -am "release: v${{ github.event.inputs.version }}"
          git push origin built

      - name: Switch to main branch
        run: |
          git switch main -f
          git push --atomic origin main v${{ github.event.inputs.version }}
